// Geo lookup + haversine distance for runtime distance ranking of service-map
// placemarks. Data is sourced from pgeocode's bundled US postal-code database
// (public-domain), pre-built into static JSON by scripts/build-geo-data.py.
//
// All three lookup tables are lazy-loaded from disk on first use and cached
// for the lifetime of the lambda. The largest (us-zip-centroids.json) is
// ~1.1 MB; loading once at cold-start is acceptable for a serverless function.

import zipCentroids from "@/data/geo/us-zip-centroids.json";
import cityCentroids from "@/data/geo/us-city-centroids.json";
import stateCentroids from "@/data/geo/us-state-centroids.json";

type LatLng = readonly [number, number];

// JSON imports type values as number[] (open arrays); we know they're 2-tuples.
// Cast through `unknown` to satisfy strict mode — this is safe given the data
// is generated by scripts/build-geo-data.py with shape [lat, lng] only.
const ZIP_CENTROIDS = zipCentroids as unknown as Readonly<Record<string, LatLng>>;
const CITY_CENTROIDS = cityCentroids as unknown as Readonly<Record<string, LatLng>>;
const STATE_CENTROIDS = stateCentroids as unknown as Readonly<Record<string, LatLng>>;

/** Look up the centroid of a 5-digit US ZIP. Returns null if unknown. */
export function getZipCentroid(zip: string): LatLng | null {
  const z = zip.trim();
  if (!/^\d{5}$/.test(z)) return null;
  return ZIP_CENTROIDS[z] ?? null;
}

/** Look up the centroid of a "CITY,STATE" pair. Case-insensitive. */
export function getCityCentroid(city: string, state: string): LatLng | null {
  const key = `${city.trim().toUpperCase()},${state.trim().toUpperCase()}`;
  return CITY_CENTROIDS[key] ?? null;
}

/** Look up the centroid of a 2-letter US state code. Case-insensitive. */
export function getStateCentroid(state: string): LatLng | null {
  return STATE_CENTROIDS[state.trim().toUpperCase()] ?? null;
}

/**
 * Haversine distance in miles between two lat/lng pairs.
 * Uses the spherical-earth approximation (radius 3958.8 mi). Accurate to
 * within ~0.5% for typical inter-city distances; plenty for ranking purposes.
 */
export function haversineMiles(a: LatLng, b: LatLng): number {
  const [lat1, lng1] = a;
  const [lat2, lng2] = b;
  const R = 3958.8; // earth radius in miles
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const φ1 = toRad(lat1);
  const φ2 = toRad(lat2);
  const sinDLat = Math.sin(dLat / 2);
  const sinDLng = Math.sin(dLng / 2);
  const h = sinDLat * sinDLat + Math.cos(φ1) * Math.cos(φ2) * sinDLng * sinDLng;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)));
}

/**
 * Detect a US location in a free-text query and resolve it to a centroid.
 * Tries, in order:
 *   1. An explicit 5-digit ZIP somewhere in the query
 *   2. A "City, ST" or "city state-name" or "city ST" form, where the city
 *      is a known place in our centroid table for the matched state
 *   3. A bare US state name or 2-letter code (case-insensitive) → state centroid
 * Returns null if no location-shaped phrase is found.
 *
 * The matched form is also returned so the slicer can include it in the
 * inline header it hands to the synthesis prompt.
 */
export type ResolvedLocation = {
  centroid: LatLng;
  /** Human-readable label for the matched location. */
  label: string;
  /** What kind of match this was — for debugging/headers. */
  resolution: "zip" | "city-state" | "state";
};

const STATE_NAME_TO_CODE: Record<string, string> = {
  alabama: "AL", alaska: "AK", arizona: "AZ", arkansas: "AR",
  california: "CA", colorado: "CO", connecticut: "CT", delaware: "DE",
  florida: "FL", georgia: "GA", hawaii: "HI", idaho: "ID",
  illinois: "IL", indiana: "IN", iowa: "IA", kansas: "KS",
  kentucky: "KY", louisiana: "LA", maine: "ME", maryland: "MD",
  massachusetts: "MA", michigan: "MI", minnesota: "MN", mississippi: "MS",
  missouri: "MO", montana: "MT", nebraska: "NE", nevada: "NV",
  "new hampshire": "NH", "new jersey": "NJ", "new mexico": "NM", "new york": "NY",
  "north carolina": "NC", "north dakota": "ND", ohio: "OH", oklahoma: "OK",
  oregon: "OR", pennsylvania: "PA", "rhode island": "RI", "south carolina": "SC",
  "south dakota": "SD", tennessee: "TN", texas: "TX", utah: "UT",
  vermont: "VT", virginia: "VA", washington: "WA", "west virginia": "WV",
  wisconsin: "WI", wyoming: "WY",
};
const VALID_STATE_CODES = new Set(Object.values(STATE_NAME_TO_CODE));

export function resolveQueryLocation(question: string): ResolvedLocation | null {
  // 1. Explicit 5-digit ZIP. Look for one preceded/followed by non-digit
  //    characters so we don't match parts of a longer number.
  const zipMatch = question.match(/(?:^|[^\d])(\d{5})(?:[^\d]|$)/);
  if (zipMatch) {
    const c = getZipCentroid(zipMatch[1]);
    if (c) return { centroid: c, label: zipMatch[1], resolution: "zip" };
  }

  // 2. City + state. Build a regex that matches a 1-3 word city followed by
  //    an optional comma and either a state name or 2-letter code.
  //    Examples we want to match (case-insensitive):
  //      "reno, nv"
  //      "Reno NV"
  //      "Pittsfield Massachusetts"
  //      "los angeles, ca"
  //
  // Strategy: find each candidate "<words> <STATE-or-name>" span, look up
  //    its centroid in the city map. Prefer the longest match (3-word city
  //    over 1-word) to handle "Los Angeles CA" vs "Los Angeles" alone.
  const stateNameAlt = Object.keys(STATE_NAME_TO_CODE).join("|");
  const stateCodeAlt = Array.from(VALID_STATE_CODES).join("|");
  // City: 1-3 capitalized-or-lowercase word tokens; allow apostrophes and hyphens.
  // We'll then look up the resolved (CITY, ST) in the city centroids table.
  const cityStateRe = new RegExp(
    `\\b([A-Za-z][A-Za-z'.\\-]*(?:\\s+[A-Za-z][A-Za-z'.\\-]*){0,2})` +
      `\\s*,?\\s+(${stateNameAlt}|${stateCodeAlt})\\b`,
    "gi"
  );
  let best: ResolvedLocation | null = null;
  for (const m of question.matchAll(cityStateRe)) {
    const city = m[1].trim();
    const stRaw = m[2].toLowerCase();
    const stCode = STATE_NAME_TO_CODE[stRaw] ?? stRaw.toUpperCase();
    if (!VALID_STATE_CODES.has(stCode)) continue;
    const centroid = getCityCentroid(city, stCode);
    if (centroid) {
      // Prefer longer city names — "Los Angeles, CA" > "Angeles, CA".
      const label = `${city.replace(/\s+/g, " ")}, ${stCode}`;
      if (!best || city.length > best.label.length) {
        best = { centroid, label, resolution: "city-state" };
      }
    }
  }
  if (best) return best;

  // 3. State only. Match the longest state-name first to avoid e.g.
  //    matching "new york" as state="york".
  const stateNames = Object.keys(STATE_NAME_TO_CODE).sort(
    (a, b) => b.length - a.length
  );
  for (const name of stateNames) {
    if (new RegExp(`\\b${name}\\b`, "i").test(question)) {
      const code = STATE_NAME_TO_CODE[name];
      const c = getStateCentroid(code);
      if (c) return { centroid: c, label: code, resolution: "state" };
    }
  }
  // 2-letter code, accepting either case (this is the bug Paul caught).
  for (const m of question.matchAll(/\b([A-Za-z]{2})\b/g)) {
    const upper = m[1].toUpperCase();
    if (VALID_STATE_CODES.has(upper)) {
      const c = getStateCentroid(upper);
      if (c) return { centroid: c, label: upper, resolution: "state" };
    }
  }

  return null;
}

/**
 * Pull a 5-digit ZIP out of a placemark address line. Most placemarks have
 * "ST 99999" or "ST 99999-9999" near the end of the address; extract the
 * 5-digit portion. Returns null if no ZIP found.
 */
export function extractZipFromAddress(address: string): string | null {
  const m = address.match(/\b([A-Z]{2})\s+(\d{5})(?:-\d{4})?\b/);
  return m ? m[2] : null;
}
