#!/usr/bin/env python3
"""
Apply Paul-supplied image URL overrides to products, generated by the
"Overrides" tab in data/.image-audit.html.

Input format (one line per override; '#' comments and blanks ignored):

    # bid-iq image overrides
    62  https://www.alltiresupply.com/products/some-page
    64  https://vendor.com/images/foo.jpg
    65  https://manufacturer.com/cdn/photo.png

Per row, the script:
  - Trims whitespace, splits on first run of whitespace.
  - If the URL ends in a recognized image extension (.jpg, .jpeg, .png,
    .webp, .gif, with optional query/fragment), treat it as a DIRECT
    image URL: store as-is into image_url, and reuse it as
    image_source_url since we have nothing else.
  - Otherwise treat it as a PAGE URL: fetch the HTML, run the same
    multi-stage extractor as the v2 scraper (og:image / twitter:image /
    JSON-LD Product.image / Magento / WP), reject bad-pattern image
    filenames, store image_url + image_source_url.
  - Always bumps image_fetched_at = NOW().

Re-runnable; doesn't touch rows you didn't list. Use --dry-run to plan.

Read from a file with --file <path>, or pipe via stdin.

    python scripts/apply-image-overrides.py --file overrides.txt
    pbpaste | python scripts/apply-image-overrides.py
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

import psycopg  # type: ignore

REPO_ROOT = Path(__file__).resolve().parent.parent

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
      "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36")

IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif")

_OG_PATTERNS = [
    r'<meta\s+property=["\']og:image["\']\s+content=["\']([^"\']+)["\']',
    r'<meta\s+content=["\']([^"\']+)["\']\s+property=["\']og:image["\']',
    r'<meta\s+name=["\']twitter:image["\']\s+content=["\']([^"\']+)["\']',
    r'<meta\s+content=["\']([^"\']+)["\']\s+name=["\']twitter:image["\']',
]

# Same bad-image filter the v2 scraper uses.
_BAD_IMAGE_PATTERNS = re.compile(
    r"(?:placeholder|/logo[-_./]|favicon|icon-|cropped[-_]cropped[-_]"
    r"|/default/|default-thumb|store-thumbnail|custom[-_]thumb"
    r"|spinner|loading\.gif|/avatar/|/svg/|\.svg(\?|$))",
    re.I,
)


def load_db_url() -> str:
    url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")
    if url:
        return url
    for envfile in (".env.local", ".env"):
        ep = REPO_ROOT / envfile
        if not ep.exists():
            continue
        for line in ep.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if "=" not in line or line.startswith("#"):
                continue
            k, v = line.split("=", 1)
            if k.strip() in ("DATABASE_URL", "POSTGRES_URL"):
                return v.strip().strip('"').strip("'")
    print("ERROR: DATABASE_URL not set", file=sys.stderr)
    sys.exit(1)


def http_get(url: str, max_bytes: int = 2_000_000) -> tuple[int, str, bytes]:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": UA, "Accept": "text/html,application/xhtml+xml,*/*"},
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return r.status, r.headers.get("Content-Type", ""), r.read(max_bytes)
    except urllib.error.HTTPError as e:
        return e.code, "", b""
    except Exception:
        return 0, "", b""


def _walk_jsonld_for_product_image(node):
    if isinstance(node, dict):
        atype = node.get("@type")
        if (
            (isinstance(atype, str) and atype.lower() == "product")
            or (isinstance(atype, list) and any(str(t).lower() == "product" for t in atype))
        ):
            img = node.get("image")
            if isinstance(img, str):
                return img
            if isinstance(img, list) and img:
                first = img[0]
                if isinstance(first, str):
                    return first
                if isinstance(first, dict):
                    return first.get("url") or first.get("@id")
            if isinstance(img, dict):
                return img.get("url") or img.get("@id")
        for v in node.values():
            r = _walk_jsonld_for_product_image(v)
            if r:
                return r
    elif isinstance(node, list):
        for v in node:
            r = _walk_jsonld_for_product_image(v)
            if r:
                return r
    return None


def extract_image_from_html(html: str) -> str | None:
    for pat in _OG_PATTERNS:
        m = re.search(pat, html, re.I)
        if m:
            cand = m.group(1).strip()
            if cand and not _BAD_IMAGE_PATTERNS.search(cand):
                return cand
    for m in re.finditer(
        r'<script[^>]+type=["\']application/ld\+json["\'][^>]*>(.*?)</script>',
        html, re.I | re.S,
    ):
        body = m.group(1).strip()
        try:
            data = json.loads(body)
        except Exception:
            try:
                data = json.loads(body.replace("&quot;", '"').replace("&amp;", "&"))
            except Exception:
                continue
        img = _walk_jsonld_for_product_image(data)
        if img and not _BAD_IMAGE_PATTERNS.search(img):
            return img
    # Magento product gallery
    for m in re.findall(
        r'https?://[^\s"\'<>]+/media/catalog/product/(?!cache/)[^\s"\'<>]+?\.(?:jpg|jpeg|png|webp)',
        html, re.I,
    ):
        if not _BAD_IMAGE_PATTERNS.search(m):
            return m
    # First non-bad WP upload
    for m in re.findall(
        r'https?://[^\s"\'<>]+/wp-content/uploads/[^\s"\'<>]+?\.(?:jpg|jpeg|png|webp)',
        html, re.I,
    ):
        if not _BAD_IMAGE_PATTERNS.search(m):
            return m
    return None


def url_looks_like_image(url: str) -> bool:
    try:
        path = urllib.parse.urlparse(url).path.lower()
    except Exception:
        return False
    return path.endswith(IMAGE_EXTS)


def url_is_image_by_content_type(url: str) -> bool:
    """Fallback for image URLs with no file extension (CDN transform
    URLs like https://*.bynder.com/transform/<uuid>/<name>?io=...).
    Cheap HEAD; if Content-Type starts with image/, treat as direct."""
    req = urllib.request.Request(
        url, headers={"User-Agent": UA, "Accept": "*/*"}, method="HEAD",
    )
    try:
        with urllib.request.urlopen(req, timeout=8) as r:
            return r.headers.get("Content-Type", "").lower().startswith("image/")
    except Exception:
        return False


def parse_overrides(stream) -> list[tuple[int, str]]:
    out: list[tuple[int, str]] = []
    for raw in stream:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            print(f"  ignoring malformed line: {line!r}", file=sys.stderr)
            continue
        id_s, url = parts
        try:
            pid = int(id_s)
        except ValueError:
            print(f"  ignoring non-integer id: {line!r}", file=sys.stderr)
            continue
        if not url.startswith(("http://", "https://")):
            print(f"  ignoring non-http url for id {pid}: {url!r}", file=sys.stderr)
            continue
        out.append((pid, url))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", help="path to override file; default: read from stdin")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    if args.file:
        with open(args.file, "r", encoding="utf-8") as f:
            overrides = parse_overrides(f)
    else:
        overrides = parse_overrides(sys.stdin)
    print(f"Overrides parsed: {len(overrides)}")
    if not overrides:
        return 0

    conn = psycopg.connect(load_db_url(), autocommit=False)
    cur = conn.cursor()

    applied = 0
    direct = 0
    extracted = 0
    failed = 0

    for pid, url in overrides:
        is_image = url_looks_like_image(url)
        if not is_image:
            # No image extension — try HEAD to see if it's an
            # extensionless image (CDN transform URLs, etc.)
            is_image = url_is_image_by_content_type(url)
        if is_image:
            # Direct image URL — trust Paul, store as-is
            if _BAD_IMAGE_PATTERNS.search(url):
                print(f"  [{pid}] REJECT (bad pattern): {url}")
                failed += 1
                continue
            image_url = url
            image_source = url
            direct += 1
            tag = "DIRECT"
        else:
            # Page URL — fetch and extract
            status, ct, data = http_get(url)
            if status != 200 or "html" not in ct.lower():
                print(f"  [{pid}] FETCH-FAIL status={status} {url}")
                failed += 1
                continue
            html = data.decode("utf-8", errors="replace")
            img = extract_image_from_html(html)
            if not img:
                print(f"  [{pid}] NO-IMG-ON-PAGE {url}")
                failed += 1
                continue
            if img.startswith("//"):
                img = "https:" + img
            elif img.startswith("/"):
                origin = "{0.scheme}://{0.netloc}".format(urllib.parse.urlparse(url))
                img = origin + img
            if _BAD_IMAGE_PATTERNS.search(img):
                print(f"  [{pid}] EXTRACTED-BAD-PATTERN {img}")
                failed += 1
                continue
            image_url = img
            image_source = url
            extracted += 1
            tag = "EXTRACTED"

        if args.verbose or applied % 10 == 0:
            print(f"  [{pid}] {tag:<9} {image_url[:96]}")

        if not args.dry_run:
            cur.execute(
                "UPDATE products SET image_url=%s, image_source_url=%s, image_fetched_at=NOW() WHERE id=%s",
                (image_url, image_source, pid),
            )
            conn.commit()
        applied += 1
        time.sleep(0.2)

    print()
    print(f"Applied:    {applied}")
    print(f"  direct:   {direct}  (URL looked like an image, stored as-is)")
    print(f"  scraped:  {extracted}  (fetched page, extracted og:image)")
    print(f"Failed:     {failed}")
    if args.dry_run:
        print("[DRY RUN] No DB writes.")
    cur.close()
    conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
